apiVersion: v1
kind: Secret
metadata: 
  name: registry
  namespace: kube-system
data:
  .dockercfg: eyJodHRwczovL2RvY2tlci5iYWlmZW5kaWFuLmNvbS92MS8iOiB7ImF1dGgiOiAiYzNsek9rUjNTRTF0ZGtGRyIsICJlbWFpbCI6ICJ5aS53dUBiYWlmZW5kaWFuLmNvbSJ9fQo=
type: kubernetes.io/dockercfg
