apiVersion: v1
kind: Service
metadata:
  name: hadoop-zookeeper
  labels:
    component: hadoop-zookeeper
spec:
  selector:
    component: hadoop-zookeeper
  ports:
  - name: userport
    port: 2181
    protocol: TCP
